import Head from 'next/head';
import Link from 'next/link';
import React from 'react';

export default function Header() {
  return (
    <header>
      <Head>
        <title>articles.day</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, user-scalable=no"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </header>
  );
}
