import Head from 'next/head';
import Link from 'next/link';
import React from 'react';

export default function Header() {
  return (
    <header>
      <Head>
        <title>reviewers</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </header>
  );
}
